version: '3'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]